
project_id = "ksiinmxsycosnpchutuw"

[global.env]
SUPABASE_URL = "https://ksiinmxsycosnpchutuw.supabase.co"
GOOGLE_MAPS_API = "{{env.GOOGLE_MAPS_API}}"
OPENAI_API_KEY = "{{env.OPENAI_API_KEY}}"
STRIPE_SECRET_KEY = "{{env.STRIPE_SECRET_KEY}}"
STRIPE_PUBLISHABLE_KEY = "{{env.STRIPE_PUBLISHABLE_KEY}}"
RESEND_API_KEY = "{{env.RESEND_API_KEY}}"
GEMINI_API_KEY = "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"
