
project_id = "ksiinmxsycosnpchutuw"

[functions.ai-assistant]
verify_jwt = true

[functions.gpt-will-assistant]
verify_jwt = false

[functions.save-will-conversation]
verify_jwt = false

[functions.send-verification]
verify_jwt = false
