// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cshnqojdrlfxbidqxwwz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNzaG5xb2pkcmxmeGJpZHF4d3d6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc5MTg0MDAsImV4cCI6MjA2MzQ5NDQwMH0.8XyR6p_Ell8rjGgTIuKDA13jsndChSjXlV4_aNYrEMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);