import React, { useState, useEffect } from 'react';
import { useNavigate } from 'react-router-dom';
import { toast } from '@/hooks/use-toast';
import confetti from 'canvas-confetti';
import { supabase } from '@/integrations/supabase/client';

// Import step components
import { UserDetailsStep } from './steps/UserDetailsStep';
import { PinSetupStep } from './steps/PinSetupStep';
import { UserBackgroundStep } from './steps/UserBackgroundStep';
import { AuthenticatorStep } from './steps/AuthenticatorStep';
import { LocationStep } from './steps/LocationStep';
import { TemplateStep } from './steps/TemplateStep';
import { KycStep } from './steps/KycStep';
import { SubscriptionStep } from './steps/SubscriptionStep';
import { SuccessStep } from './steps/SuccessStep';

// Import types and Stepper
import { Stepper } from './Stepper';
import { 
  SignUpStep, 
  UserDetailsInputs, 
  PinInputs, 
  UserBackgroundInputs, 
  LocationInputs, 
  TemplateInputs, 
  KycInputs, 
  SubscriptionInputs
} from './SignUpSchemas';

export function SignUpForm() {
  // State management for multi-step form
  const [step, setStep] = useState<SignUpStep>(1);
  const [userDetails, setUserDetails] = useState<UserDetailsInputs | null>(null);
  const [pinDetails, setPinDetails] = useState<PinInputs | null>(null);
  const [userBackground, setUserBackground] = useState<UserBackgroundInputs | null>(null);
  const [authenticatorKey, setAuthenticatorKey] = useState<string>('');
  const [qrCodeUrl, setQrCodeUrl] = useState<string>('');
  const [location, setLocation] = useState<LocationInputs>({
    country: 'United States',
    city: 'New York'
  });
  const [templateChoice, setTemplateChoice] = useState<string>('');
  const [willPreview, setWillPreview] = useState<string>('');
  const [kycData, setKycData] = useState<KycInputs | null>(null);
  const [subscription, setSubscription] = useState<SubscriptionInputs | null>(null);
  
  const navigate = useNavigate();
  
  // Generate authenticator key when reaching step 4
  useEffect(() => {
    if (step === 4 && !authenticatorKey) {
      const characters = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567';
      let result = '';
      for (let i = 0; i < 16; i++) {
        result += characters.charAt(Math.floor(Math.random() * characters.length));
        if (i % 4 === 3 && i < 15) result += ' ';
      }
      setAuthenticatorKey(result);
      
      const email = userDetails?.email || 'user@example.com';
      setQrCodeUrl('https://chart.googleapis.com/chart?chs=200x200&chld=M|0&cht=qr&chl=otpauth://totp/WillTank:' + 
                  encodeURIComponent(email) + '%3Fsecret%3D' + result.replace(/\s/g, '') + '%26issuer%3DWillTank');
    }
  }, [step, authenticatorKey, userDetails]);
  
  // Generate will preview when reaching step 6
  useEffect(() => {
    if (step === 6 && !willPreview) {
      const firstName = userDetails?.firstName || 'John';
      const lastName = userDetails?.lastName || 'Doe';
      const isMarried = userBackground?.isMarried === 'yes';
      const hasChildren = userBackground?.hasChildren === 'yes';
      
      setWillPreview(`
LAST WILL AND TESTAMENT OF ${firstName.toUpperCase()} ${lastName.toUpperCase()}

I, ${firstName} ${lastName}, a resident of ${location.city || 'City'}, ${location.country || 'Country'}, being of sound mind, declare this to be my Last Will and Testament.

ARTICLE I - REVOCATION
I revoke all prior wills and codicils.

ARTICLE II - FAMILY STATUS
${isMarried ? 'I am married to [Spouse Name].' : 'I am not currently married.'}
${hasChildren ? 'I have children whose names are [Child Names].' : 'I do not currently have any children.'}

ARTICLE III - EXECUTOR APPOINTMENT
I appoint [Executor Name] as Executor of my estate.

ARTICLE IV - DISTRIBUTION OF ASSETS
I give all of my property, real and personal, to [Beneficiary Names].

ARTICLE V - SPECIFIC BEQUESTS
[List of specific items and who they go to]

This document is a preview generated by WillTank's AI system. It is not a legal document and would require customization, verification, and proper execution to be valid.
      `);
    }
  }, [step, willPreview, userDetails, userBackground, location]);

  const onUserDetailsSubmit = (data: UserDetailsInputs) => {
    setUserDetails(data);
    setStep(2);
  };

  const onPinSubmit = (data: PinInputs) => {
    setPinDetails(data);
    setStep(3);
  };
  
  const onUserBackgroundSubmit = (data: UserBackgroundInputs) => {
    setUserBackground(data);
    setStep(4);
  };
  
  const onAuthenticatorSubmit = () => {
    setStep(5);
  };
  
  const onLocationSubmit = (data: LocationInputs) => {
    setLocation(data);
    setStep(6);
  };
  
  const onTemplateSubmit = (data: TemplateInputs) => {
    setTemplateChoice(data.templateChoice);
    setStep(7);
  };
  
  const onKycSubmit = (data: KycInputs) => {
    setKycData(data);
    setStep(8);
  };
  
  const onSubscriptionSubmit = (data: SubscriptionInputs) => {
    setSubscription(data);
    
    const formData = {
      ...userDetails,
      ...pinDetails,
      userBackground,
      authenticatorKey,
      location,
      templateChoice,
      kycData,
      subscription: data,
    };
    
    console.log('Form data submitted:', formData);
    
    toast({
      title: "Account created!",
      description: "Your WillTank account has been successfully created.",
    });
    
    confetti({
      particleCount: 100,
      spread: 70,
      origin: { y: 0.6 }
    });
    
    setStep(9);
    
    setTimeout(() => {
      navigate('/dashboard');
    }, 3000);
  };

  // Updated total steps (removed TanKey and RecoveryPhrase steps)
  const totalSteps = 8;

  return (
    <div className="w-full">
      <Stepper currentStep={step} totalSteps={totalSteps} />
      
      {/* Step 1: User Details */}
      {step === 1 && <UserDetailsStep onNext={onUserDetailsSubmit} />}
      
      {/* Step 2: PIN Setup */}
      {step === 2 && <PinSetupStep onNext={onPinSubmit} />}
      
      {/* Step 3: User Background */}
      {step === 3 && <UserBackgroundStep onNext={onUserBackgroundSubmit} />}
      
      {/* Step 4: Authenticator Setup */}
      {step === 4 && (
        <AuthenticatorStep 
          authenticatorKey={authenticatorKey} 
          qrCodeUrl={qrCodeUrl} 
          onNext={onAuthenticatorSubmit} 
        />
      )}
      
      {/* Step 5: Location Setup */}
      {step === 5 && (
        <LocationStep 
          defaultLocation={location} 
          onNext={onLocationSubmit} 
        />
      )}
      
      {/* Step 6: Template Selection */}
      {step === 6 && (
        <TemplateStep 
          willPreview={willPreview} 
          onNext={onTemplateSubmit} 
        />
      )}
      
      {/* Step 7: Identity Verification (KYC) */}
      {step === 7 && <KycStep onNext={onKycSubmit} />}
      
      {/* Step 8: Subscription Selection */}
      {step === 8 && <SubscriptionStep onNext={onSubscriptionSubmit} />}
      
      {/* Success Step - Shown briefly after subscription */}
      {step === 9 && <SuccessStep />}
    </div>
  );
}
